// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/hello": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "example"
                ],
                "summary": "hello world",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/hello2": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "example"
                ],
                "summary": "hello world",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/ping": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "ping and pong",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        }
    },
    "externalDocs": {
        "url": "https://swagger.io/resources/open-api/"
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "3.1.0",
	Host:             "localhost:8009",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Demo Gin API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
