basePath: /api/v1
externalDocs:
  url: https://swagger.io/resources/open-api/
host: localhost:8009
info:
  contact: {}
  title: Demo Gin API
  version: 3.1.0
paths:
  /hello:
    get:
      consumes:
      - application/json
      responses:
        "200":
          description: OK
      summary: hello world
      tags:
      - example
  /hello2:
    get:
      consumes:
      - application/json
      responses:
        "200":
          description: OK
      summary: hello world
      tags:
      - example
  /ping:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: ping and pong
swagger: "2.0"
